version: 2.1

executors:
  golang-latest:
    docker:
      - image: cimg/go:1.16

commands:
  install_terraform:
    description: install terraform in go container
    steps:
      - run:
          name: Install terraform
          environment:
            TF_VERSION: 1.9.3
          command: |
            mkdir -p ~/bin
            cd ~/bin
            wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip terraform_${TF_VERSION}_linux_amd64.zip
            echo 'export PATH=~/bin:$PATH'  >> $BASH_ENV
            terraform --version
  run_tests:
    parameters:
      test_name:
        type: string
      test_timeout:
        type: string
    description: run terratest tests
    steps:
      - run:
          name: Run tests
          command: |
            cd test/src
            go version
            go mod download
            go test -v -timeout << parameters.test_timeout >> -run << parameters.test_name >>

jobs:
  run-terratest-tests-dev:
    executor: golang-latest
    steps:
      - checkout
      - install_terraform
      - run_tests:
          test_name: TestExamplesComplete
          test_timeout: 15m

workflows:
  on-commit:
    jobs:
      - run-terratest-tests-dev
